server:
  port: 8093

spring:
  application:
    name: niffler-spend
  datasource:
    hikari:
      pool-name: ${spring.application.name}-pool
      connection-timeout: 20000
      minimum-idle: 15
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1800000
      keepalive-time: 120000
      leak-detection-threshold: 30000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/niffler-spend
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/niffler-spend'
    username: postgres
    password: secret
grpc:
  client:
    grpcCurrencyClient:
      address: 'static://localhost:8092'
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: 'http://localhost:8091'
niffler-userdata:
  base-uri: 'http://localhost:8089'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:postgresql://niffler-all-db:5432/niffler-spend'
    username: postgres
    password: secret
grpc:
  client:
    grpcCurrencyClient:
      address: 'static://currency.niffler.dc:8092'
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: 'http://currency.niffler.dc:8091'
niffler-userdata:
  base-uri: 'http://userdata.niffler.dc:8089'
---
spring:
  config:
    activate:
      on-profile: 'prod'
  datasource:
    url: ${SPEND_DB_URL}
    username: ${SPEND_DB_USERNAME}
    password: ${SPEND_DB_PASSWORD}
grpc:
  client:
    grpcCurrencyClient:
      address: ${SPEND_NIFFLER_CURRENCY_GRPC_URL}
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: ${SPEND_NIFFLER_CURRENCY_URL}
niffler-userdata:
  base-uri: ${SPEND_NIFFLER_USERDATA_URL}
---
spring:
  config:
    activate:
      on-profile: 'staging'
  datasource:
    url: ${SPEND_DB_URL}
    username: ${SPEND_DB_USERNAME}
    password: ${SPEND_DB_PASSWORD}
grpc:
  client:
    grpcCurrencyClient:
      address: ${SPEND_NIFFLER_CURRENCY_GRPC_URL}
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: ${SPEND_NIFFLER_CURRENCY_URL}
niffler-userdata:
  base-uri: ${SPEND_NIFFLER_USERDATA_URL}
---