services:
  auth.niffler.dc:
    container_name: auth.niffler.dc
    image: ${PREFIX}/niffler-auth-${PROFILE}:${AUTH_VER}
    pull_policy: always
    mem_limit: 1600m
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=1024m -XX:MaxHeapSize=1024m
      - AUTH_DB_URL
      - AUTH_DB_USERNAME
      - AUTH_DB_PASSWORD
      - AUTH_KAFKA_URL
      - AUTH_WEB_CLIENT_ID
      - AUTH_MOBILE_CLIENT_ID
      - AUTH_MOBILE_CUSTOM_SCHEME
      - AUTH_ANDROID_APP_URI
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9000:9000
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - niffler-network

  currency.niffler.dc:
    container_name: currency.niffler.dc
    image: ${PREFIX}/niffler-currency-${PROFILE}:${CURRENCY_VER}
    pull_policy: always
    mem_limit: 1200m
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=768m -XX:MaxHeapSize=768m
      - CURRENCY_DB_URL
      - CURRENCY_DB_USERNAME
      - CURRENCY_DB_PASSWORD
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8091:8091
      - 8092:8092
    restart: always
    networks:
      - niffler-network

  gateway.niffler.dc:
    container_name: gateway.niffler.dc
    image: ${PREFIX}/niffler-gateway-${PROFILE}:${GATEWAY_VER}
    pull_policy: always
    mem_limit: 1200m
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=768m -XX:MaxHeapSize=768m
      - GATEWAY_NIFFLER_CURRENCY_GRPC_URL
      - GATEWAY_NIFFLER_CURRENCY_URL
      - GATEWAY_NIFFLER_USERDATA_URL
      - GATEWAY_NIFFLER_SPEND_URL
    ports:
      - 8090:8090
    healthcheck:
      test: "wget --spider http://localhost:8090/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      auth.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network

  spend.niffler.dc:
    container_name: spend.niffler.dc
    image: ${PREFIX}/niffler-spend-${PROFILE}:${SPEND_VER}
    pull_policy: always
    mem_limit: 1600m
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=1024m -XX:MaxHeapSize=1024m
      - SPEND_DB_URL
      - SPEND_DB_USERNAME
      - SPEND_DB_PASSWORD
      - SPEND_NIFFLER_CURRENCY_GRPC_URL
      - SPEND_NIFFLER_CURRENCY_URL
      - SPEND_NIFFLER_USERDATA_URL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8093:8093
    restart: always
    networks:
      - niffler-network

  userdata.niffler.dc:
    container_name: userdata.niffler.dc
    image: ${PREFIX}/niffler-userdata-${PROFILE}:${USERDATA_VER}
    pull_policy: always
    mem_limit: 1200m
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=768m -XX:MaxHeapSize=768m
      - USERDATA_DB_URL
      - USERDATA_DB_USERNAME
      - USERDATA_DB_PASSWORD
      - USERDATA_KAFKA_URL
      - USERDATA_NIFFLER_USERDATA_URL
      - USERDATA_FIREBASE_KEY
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8089:8089
    restart: always
    depends_on:
      auth.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network

  frontend.niffler.dc:
    container_name: frontend.niffler.dc
    image: ${PREFIX}/niffler-ng-client-${PROFILE}:${FRONT_VER}
    pull_policy: always
    ports:
      - 8000:80
    restart: always
    depends_on:
      gateway.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network

networks:
  niffler-network:
    driver: bridge
