//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package niffler.model.soap;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for friendState.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="friendState">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="INVITE_SENT"/>
 *     <enumeration value="INVITE_RECEIVED"/>
 *     <enumeration value="FRIEND"/>
 *     <enumeration value="VOID"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "friendState")
@XmlEnum
public enum FriendState {

    INVITE_SENT,
    INVITE_RECEIVED,
    FRIEND,
    VOID;

    public String value() {
        return name();
    }

    public static FriendState fromValue(String v) {
        return valueOf(v);
    }

}
