server:
  port: 8090

spring:
  application:
    name: niffler-gateway
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    net.devh.boot.grpc: INFO
    org.springframework.boot.autoconfigure: INFO

niffler-userdata:
  client: soap

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:9000'
  graphql:
    graphiql:
      enabled: true

grpc:
  client:
    grpcCurrencyClient:
      address: 'static://localhost:8092'
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: 'http://localhost:8091'
niffler-userdata:
  base-uri: 'http://localhost:8089'
niffler-spend:
  base-uri: 'http://localhost:8093'
niffler-front:
  base-uri: 'http://localhost:3000'
niffler-gateway:
  base-uri: 'http://localhost:8090'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.niffler.dc:9000'

grpc:
  client:
    grpcCurrencyClient:
      address: 'static://currency.niffler.dc:8092'
      negotiationType: PLAINTEXT

niffler-currency:
  base-uri: 'http://currency.niffler.dc:8091'
niffler-userdata:
  base-uri: 'http://userdata.niffler.dc:8089'
niffler-spend:
  base-uri: 'http://spend.niffler.dc:8093'
niffler-front:
  base-uri: 'http://frontend.niffler.dc'
niffler-gateway:
  base-uri: 'http://gateway.niffler.dc:8090'
---
spring:
  config:
    activate:
      on-profile: 'prod'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.niffler.qa.guru'

grpc:
  client:
    grpcCurrencyClient:
      address: ${GATEWAY_NIFFLER_CURRENCY_GRPC_URL}
      negotiationType: PLAINTEXT

server:
  tomcat:
    remoteip:
      port-header: 'x-forwarded-for'
      protocol-header: 'x-forwarded-proto'

niffler-currency:
  base-uri: ${GATEWAY_NIFFLER_CURRENCY_URL}
niffler-userdata:
  base-uri: ${GATEWAY_NIFFLER_USERDATA_URL}
niffler-spend:
  base-uri: ${GATEWAY_NIFFLER_SPEND_URL}
niffler-front:
  base-uri: 'https://niffler.qa.guru'
niffler-gateway:
  base-uri: 'https://api.niffler.qa.guru'
---
spring:
  config:
    activate:
      on-profile: 'staging'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.niffler-stage.qa.guru'

grpc:
  client:
    grpcCurrencyClient:
      address: ${GATEWAY_NIFFLER_CURRENCY_GRPC_URL}
      negotiationType: PLAINTEXT

server:
  tomcat:
    remoteip:
      port-header: 'x-forwarded-for'
      protocol-header: 'x-forwarded-proto'

niffler-currency:
  base-uri: ${GATEWAY_NIFFLER_CURRENCY_URL}
niffler-userdata:
  base-uri: ${GATEWAY_NIFFLER_USERDATA_URL}
niffler-spend:
  base-uri: ${GATEWAY_NIFFLER_SPEND_URL}
niffler-front:
  base-uri: 'https://niffler-stage.qa.guru'
niffler-gateway:
  base-uri: 'https://api.niffler-stage.qa.guru'
---