server:
  port: 8091

grpc:
  server:
    port: 8092
    max-inbound-message-size: 1MB

spring:
  application:
    name: niffler-currency
  datasource:
    hikari:
      pool-name: ${spring.application.name}-pool
      connection-timeout: 20000
      minimum-idle: 15
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1800000
      keepalive-time: 120000
      leak-detection-threshold: 30000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/niffler-currency
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    username: postgres
    password: secret
    url: 'jdbc:postgresql://localhost:5432/niffler-currency'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    username: postgres
    password: secret
    url: 'jdbc:postgresql://niffler-all-db:5432/niffler-currency'
---
spring:
  config:
    activate:
      on-profile: 'prod'
  datasource:
    url: ${CURRENCY_DB_URL}
    username: ${CURRENCY_DB_USERNAME}
    password: ${CURRENCY_DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: 'staging'
  datasource:
    url: ${CURRENCY_DB_URL}
    username: ${CURRENCY_DB_USERNAME}
    password: ${CURRENCY_DB_PASSWORD}
---