server:
  port: 8089

spring:
  application:
    name: niffler-userdata
  datasource:
    hikari:
      pool-name: ${spring.application.name}-pool
      connection-timeout: 20000
      minimum-idle: 15
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1800000
      keepalive-time: 120000
      leak-detection-threshold: 30000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/niffler-userdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.ws: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:postgresql://localhost:5432/niffler-userdata'
    username: postgres
    password: secret
niffler-userdata:
  base-uri: 'http://localhost:8089'
firebase:
  enabled: false
  path: ${GOOGLE_APPLICATION_CREDENTIALS:}
---
spring:
  config:
    activate:
      on-profile: 'docker'
  kafka:
    bootstrap-servers: 'kafka:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:postgresql://niffler-all-db:5432/niffler-userdata'
    username: postgres
    password: secret
niffler-userdata:
  base-uri: 'http://userdata.niffler.dc:8089'
firebase:
  enabled: false
---
spring:
  config:
    activate:
      on-profile: 'prod'
  kafka:
    bootstrap-servers: ${USERDATA_KAFKA_URL}
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: ${USERDATA_DB_URL}
    username: ${USERDATA_DB_USERNAME}
    password: ${USERDATA_DB_PASSWORD}
niffler-userdata:
  base-uri: ${USERDATA_NIFFLER_USERDATA_URL}
firebase:
  enabled: true
  config: ${USERDATA_FIREBASE_KEY}
---
spring:
  config:
    activate:
      on-profile: 'staging'
  kafka:
    bootstrap-servers: ${USERDATA_KAFKA_URL}
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: ${USERDATA_DB_URL}
    username: ${USERDATA_DB_USERNAME}
    password: ${USERDATA_DB_PASSWORD}
niffler-userdata:
  base-uri: ${USERDATA_NIFFLER_USERDATA_URL}
firebase:
  enabled: true
  config: ${USERDATA_FIREBASE_KEY}
---