name: currency_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-currency-prod.yaml'
      - 'niffler-currency/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: currency
      compose-service: currency.niffler.dc
      gradle-module: ':niffler-currency:jib'
    secrets: inherit
