name: spend_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-spend-prod.yaml'
      - 'niffler-spend/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: spend
      compose-service: spend.niffler.dc
      gradle-module: ':niffler-spend:jib'
    secrets: inherit
