name: frontend_deploy_stage
on:
  push:
    branches:
      - ci
    paths:
      - 'niffler-frontend/**'

jobs:
  checkout:
    runs-on: stage-runner
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: stage-runner
    needs: checkout
    steps:
      - name: deploy
        working-directory: ./
        run: |
          pwd
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          bash ./docker-compose-ci.sh staging push
      - name: deploy
        run: |
          PREFIX=${{ vars.DOCKER_HUB_ACC }} PROFILE=staging FRONT_IMAGE=${{ vars.DOCKER_HUB_ACC }}/niffler-frontend-staging docker-compose -f docker-compose.ci.yml up -d --force-recreate frontend.niffler.dc
          docker system prune  -a -f
          echo "done"
