name: auth_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-auth-prod.yaml'
      - 'niffler-auth/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: auth
      compose-service: auth.niffler.dc
      gradle-module: ':niffler-auth:jib'
    secrets: inherit
