name: gateway_deploy_stage
on:
  push:
    branches: 
      - ci
    paths:
      - 'niffler-gateway/**'
      
jobs:
  checkout:
    runs-on: stage-runner  
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: stage-runner
    needs: checkout
    steps:  
      - name: deploy
        working-directory: ./
        run: |
         pwd
         bash ./docker-compose-dev.sh
         docker-compose up -d --force-recreate niffler-gateway
         docker system prune  -a -f
         echo "done"
