name: auth_deploy_stage
on:
  push:
    branches: 
      - develop
    paths:
      - 'niffler-auth/**'
      
jobs:
  checkout:
    runs-on: stage-runner  
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: stage-runner
    needs: checkout
    steps:  
      - name: deploy
        working-directory: ./niffler-auth
        env:
          DOCKER: eclipse-temurin:19-jdk
          
        run: |
         pwd
         docker system prune -a -f
         docker build -t niffler-auth:latest --build-arg DOCKER=${DOCKER} .
         docker stop niffler-auth
         docker-compose up -d
         echo "done"
