name: gateway_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-gateway-prod.yaml'
      - 'niffler-gateway/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: gateway
      compose-service: gateway.niffler.dc
      gradle-module: ':niffler-gateway:jib'
    secrets: inherit
