name: frontend_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-ng-client-prod.yaml'
      - 'niffler-ng-client/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: frontend
      compose-service: frontend.niffler.dc
      npm-command: 'build:prod'
    secrets: inherit
