name: frontend_deploy_stage
on:
  push:
    branches: 
      - develop
    paths:
      - 'niffler-frontend/**'
      
jobs:
  checkout:
    runs-on: stage-runner  
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: stage-runner
    needs: checkout
    steps:  
      - name: deploy
        working-directory: ./niffler-frontend
        env:
         IMAGE_NAME: ${{ vars.IMAGE_NAME_FRONTEND }}
         NPM_COMMAND: ${{ vars.NPM_COMMAND_FRONTEND }}
         REACT_APP_ENV: test
         REACT_APP_FRONT_URL: http://${{ vars.REACT_APP_AUTH_URL }}
         REACT_APP_AUTH_URL: http://${{ vars.REACT_APP_AUTH_URL }}:9000
         REACT_APP_GATEWAY_URL: http://${{ vars.REACT_APP_AUTH_URL }}:8090
        run: |
         pwd
         env > .env
         docker system prune -a -f
         docker build . --build-arg NPM_COMMAND=${NPM_COMMAND} -t ${IMAGE_NAME}:latest
         docker stop niffler-frontend 
      - name: deploy
        run : |
         docker-compose up -d niffler-frontend
         echo "done"

