name: auth_deploy_stage
on:
  push:
    branches: 
      - ci
    paths:
      - 'niffler-auth/**'
      
jobs:
  checkout:
    runs-on: stage-runner  
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: stage-runner
    needs: checkout
    steps:  
      - name: deploy
        working-directory: ./niffler-auth
        env:
          #DOCKER: eclipse-temurin:19-jdk
          APP_VER: 0.0.3-SNAPSHOT
        run: |
         gradle build
         docker build -t niffler-auth:latest --build-arg APP_VER=${APP_VER} .
         docker stop niffler-auth
      - name: deploy
        run : |
         docker-compose up -d niffler-auth
         echo "done"
