name: auth_deploy_prod
on:
  push:
    branches: 
      - ci-prod
    paths:
      - 'niffler-auth/**'
      
jobs:
  checkout:
    runs-on: prod-runner  
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: prod-runner
    needs: checkout
    steps:  
      - name: deploy
        working-directory: ./
        run: |
         pwd
         bash ./docker-compose-dev.sh
         docker-compose up -d --force-recreate niffler-auth
         docker system prune  -a -f
         echo "done"
      - name: push
        run: |
         docker login
         docker tag dtuchs/niffler-auth:latest ${{ vars.DOCKER_HUB_ACC }}/niffler-auth:${{github.run_number}}
         docker push ${{ vars.DOCKER_HUB_ACC }}/niffler-auth:${{github.run_number}}
