name: userdata_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/niffler-userdata-prod.yaml'
      - 'niffler-userdata/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod.yml
    with:
      service-name: userdata
      compose-service: userdata.niffler.dc
      gradle-module: ':niffler-userdata:jib'
    secrets: inherit
