name: vault_test
on:
  push:
    branches: 
      - ci-prod
      
jobs:
  build:
    runs-on: prod-runner
    steps:
      - name: import secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.qa.guru
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            secret/ci app_secret | SECRET
      - name: show secrets
        run: |
          echo "${{ steps.import-secrets.outputs.SECRET }}"
          touch secrets.json
          echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
          cat secrets.json
          echo $SECRET
