name: vault_test
on:
  push:
    branches: 
      - ci-prod
      
jobs:
  build:
    runs-on: prod-runner
    steps:
      - name: import secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.qa.guru
          token: $ {{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          caCertificate: $ {{ secrets.VAULT_CA_CERT }}
          secrets: |
            /cubbyhole/data/path/secret secret;
            /cubbyhole/path/secret secret;
            /cubbyhole/path secret ;
            /cubbyhole/data/path secret;
            /cubbyhole/path/data/secret secret ;
            /subbyhole/path/data secret;
            /kv/data/secret secret ;
      - name: show secrets
        run: |
          echo "${{ toJson(steps.import-secrets.outputs) }}"
