name: vault_test
on:
  push:
    branches: 
      - ci-prod
      
jobs:
  build:
    runs-on: prod-runner
    steps:
      - name: import secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.qa.guru
          token: $ {{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          caCertificate: $ {{ secrets.VAULT_CA_CERT }}
          secrets: |
            kv/data/secret/gh ghsecret ;
            kv/secret/gh ghsecret ;
      - name: show secrets
        run: |
          echo "${{ toJson(steps.import-secrets.outputs) }}"
