on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    outputs:
      auth-ver:
        value: ${{ jobs.collect-versions.outputs.auth }}
      currency-ver:
        value: ${{ jobs.collect-versions.outputs.currency }}
      gateway-ver:
        value: ${{ jobs.collect-versions.outputs.gateway }}
      spend-ver:
        value: ${{ jobs.collect-versions.outputs.spend }}
      userdata-ver:
        value: ${{ jobs.collect-versions.outputs.userdata }}
      front-ver:
        value: ${{ jobs.collect-versions.outputs.front }}

jobs:
  collect-versions:
    runs-on: "${{ inputs.runner }}"
    outputs:
      auth: ${{ steps.all_versions.outputs.auth }}
      currency: ${{ steps.all_versions.outputs.currency }}
      gateway: ${{ steps.all_versions.outputs.gateway }}
      spend: ${{ steps.all_versions.outputs.spend }}
      userdata: ${{ steps.all_versions.outputs.userdata }}
      front: ${{ steps.all_versions.outputs.front }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Retrieve versions for all modules
        id: all_versions
        run: |
          set -euo pipefail
          ./gradlew printAllVersions -q --console=plain -Dorg.gradle.warning.mode=none
          FRONT_VERSION=$(jq -r '.version' niffler-ng-client/package.json)
          echo "front=$FRONT_VERSION" >> "$GITHUB_OUTPUT"
      - name: Summary info
        run: |
          {
            echo "## Versions Summary"
            echo
            echo "| Service | Version |"
            echo "|---|---|"
            echo "| niffler-auth | ${{ steps.all_versions.outputs.auth }} |"
            echo "| niffler-currency | ${{ steps.all_versions.outputs.currency }} |"
            echo "| niffler-gateway | ${{ steps.all_versions.outputs.gateway }} |"
            echo "| niffler-spend | ${{ steps.all_versions.outputs.spend }} |"
            echo "| niffler-userdata | ${{ steps.all_versions.outputs.userdata }} |"
            echo "| niffler-client | ${{ steps.all_versions.outputs.front }} |"
          } >> "$GITHUB_STEP_SUMMARY"
