apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: niffler-feature-template
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pggorbachev/niffler.git
    targetRevision: HEAD
    path: argocd-manifests/niffler-feature-template
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true