apiVersion: apps/v1
kind: Deployment
metadata:
  name: niffler-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niffler-frontend
  template:
    metadata:
      labels:
        app: niffler-frontend
    spec:
      containers:
        - name: frontend
          image: niffler-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ENV
              value: "feature"